darkube_build_mori-front_mori-ai_hamravesh-c11:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  interruptible: true
  only:
    refs:
    - main
  script:
  - IMAGE_ADDRESS="registry.hamdocker.ir/mori-ai/mori-front"
  - 'darkube build --push -t $IMAGE_ADDRESS:$CI_COMMIT_SHORT_SHA -t $IMAGE_ADDRESS:$CI_COMMIT_REF_SLUG
    --workdir . --file ./Dockerfile --build-context . '
  stage: build
darkube_deploy_mori-front_mori-ai_hamravesh-c11:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  interruptible: true
  only:
    refs:
    - main
  script:
  - darkube deploy --token ${DEPLOY_TOKEN_MORI_FRONT_MORI_AI_HAMRAVESH_C11} --app-id
    ${APP_ID_MORI_FRONT_MORI_AI_HAMRAVESH_C11} --image-tag ${CI_COMMIT_SHORT_SHA}
    --job-id ${CI_JOB_ID}
  stage: deploy
